name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install ubuntu dependencies needed for Playwright
        run: sudo apt-get install ffmpeg
        if: matrix.os == 'ubuntu-18.04'
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn types
      - name: Unit Tests
        run: yarn test:unit
      - name: Build
        run: yarn build
      - name: Prepare for Integration Tests
        run: yarn demo:setup
      - name: Integration Tests
        run: yarn test:integrationOnly
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: demo/sarif-test-results
